---
- src: https://github.com/carlosfrias/apigee-opdk-setup-default-settings

- src: https://github.com/carlosfrias/apigee-opdk-server-self

- src: https://github.com/carlosfrias/apigee-opdk-setup-qpid-add

- src: https://github.com/carlosfrias/apigee-opdk-setup-qpid-remove
